version: '3'
services:
  golang:
    restart: always
    build: .
    ports:
      - 8999:8999
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: